### ISSUE TITLE
Developed a gem to use Fluffy with RoR

### ISSUE THREAD

**Issue by bastienrobert** [mzdr/fluffy.js#3]
Hi, I've developed a gem to use Fluffy with Ruby on Rails asset pipeline.
Just want to notice you about it. It's disponible here : https://rubygems.org/gems/fluffyjs
or on my Github repository : https://github.com/bastienrobert/fluffyjs-gem

Have a nice day !

**Comment by mzdr** [comment]
Hey @bastienrobert!

That is so awesome. Thanks a lot for your help and contribution! 👍
